In [14]:
import pandas as pd
df = pd.read_csv('../datasets/heart.csv')

In [15]:
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [16]:
df.shape

(920, 16)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    int64
 2   sex       920 non-null    str
 3   dataset   920 non-null    str
 4   cp        920 non-null    str
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    str
 9   thalch    865 non-null    float64
 10  exang     865 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    str
 13  ca        309 non-null    float64
 14  thal      434 non-null    str
 15  num       920 non-null    int64
dtypes: float64(5), int64(3), object(2), str(6)
memory usage: 115.1+ KB

In [18]:
df.isnull().sum()

id            0
age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

In [19]:
df.describe()

,id,age,trestbps,chol,thalch,oldpeak,ca,num
count,920.000000,920.000000,861.000000,890.000000,865.000000,858.000000,309.000000,920.000000
mean,460.500000,53.510870,132.132404,199.130337,137.545665,0.878788,0.676375,0.995652
std,265.725422,9.424685,19.066070,110.780810,25.926276,1.091226,0.935653,1.142693
min,1.000000,28.000000,0.000000,0.000000,60.000000,-2.600000,0.000000,0.000000
25%,230.750000,47.000000,120.000000,175.000000,120.000000,0.000000,0.000000,0.000000
50%,460.500000,54.000000,130.000000,223.000000,140.000000,0.500000,0.000000,1.000000
75%,690.250000,60.000000,140.000000,268.000000,157.000000,1.500000,1.000000,2.000000
max,920.000000,77.000000,200.000000,603.000000,202.000000,6.200000,3.000000,4.000000

In [20]:
df['num'].value_counts()

num
0    411
1    265
2    109
3    107
4     28
Name: count, dtype: int64

In [23]:
df.drop(['id', 'ca', 'thal'], axis=1, inplace=True)

In [24]:
df['target'] = (df['num'] > 0).astype(int)

In [25]:
df.drop('num', axis=1, inplace=True)

In [26]:
df.isnull().sum()

age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
target        0
dtype: int64

In [33]:
numerical_cols = [
    'trestbps',
    'chol',
    'thalch',
    'oldpeak'
]

for col in numerical_cols:
    df[col] = df[col].fillna(df[col].median())

In [35]:
categorical_cols = [
    'fbs',
    'restecg',
    'exang',
    'slope'
]

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [36]:
df.isnull().sum()

age         0
sex         0
dataset     0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalch      0
exang       0
oldpeak     0
slope       0
target      0
dtype: int64

In [37]:
from sklearn.preprocessing import LabelEncoder

In [38]:
le = LabelEncoder()

In [ ]:
categorical_cols = [
    'sex',
    'dataset',
    'cp',
    'fbs',
    'restecg',
    'exang',
    'slope'
]

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       920 non-null    int64
 1   sex       920 non-null    int64
 2   dataset   920 non-null    int64
 3   cp        920 non-null    int64
 4   trestbps  920 non-null    float64
 5   chol      920 non-null    float64
 6   fbs       920 non-null    int64
 7   restecg   920 non-null    int64
 8   thalch    920 non-null    float64
 9   exang     920 non-null    int64
 10  oldpeak   920 non-null    float64
 11  slope     920 non-null    int64
 12  target    920 non-null    int64
dtypes: float64(4), int64(9)
memory usage: 93.6 KB

In [41]:
X = df.drop('target', axis=1)

y = df['target']

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       920 non-null    int64
 1   sex       920 non-null    int64
 2   dataset   920 non-null    int64
 3   cp        920 non-null    int64
 4   trestbps  920 non-null    float64
 5   chol      920 non-null    float64
 6   fbs       920 non-null    int64
 7   restecg   920 non-null    int64
 8   thalch    920 non-null    float64
 9   exang     920 non-null    int64
 10  oldpeak   920 non-null    float64
 11  slope     920 non-null    int64
 12  target    920 non-null    int64
dtypes: float64(4), int64(9)
memory usage: 93.6 KB

In [47]:
X_train.shape
X_test.shape

(184, 12)

In [48]:
print(X_train.shape)
print(X_test.shape)

(736, 12)
(184, 12)

In [49]:
from sklearn.linear_model import LogisticRegression

In [50]:
lr = LogisticRegression()

In [51]:
lr.fit(X_train, y_train)

LogisticRegression()

In [52]:
y_pred = lr.predict(X_test)

In [53]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

In [54]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

Accuracy : 0.7934782608695652
Precision: 0.8585858585858586
Recall   : 0.7798165137614679
F1 Score : 0.8173076923076923

In [55]:
from sklearn.ensemble import RandomForestClassifier

In [56]:
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

In [57]:
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [58]:
rf_pred = rf.predict(X_test)

In [59]:
print("Accuracy :", accuracy_score(y_test, rf_pred))
print("Precision:", precision_score(y_test, rf_pred))
print("Recall   :", recall_score(y_test, rf_pred))
print("F1 Score :", f1_score(y_test, rf_pred))

Accuracy : 0.8369565217391305
Precision: 0.8623853211009175
Recall   : 0.8623853211009175
F1 Score : 0.8623853211009175

In [60]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.1,
    random_state=42
)

xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)

In [61]:
print("Accuracy :", accuracy_score(y_test, xgb_pred))
print("Precision:", precision_score(y_test, xgb_pred))
print("Recall   :", recall_score(y_test, xgb_pred))
print("F1 Score :", f1_score(y_test, xgb_pred))

Accuracy : 0.8315217391304348
Precision: 0.89
Recall   : 0.8165137614678899
F1 Score : 0.8516746411483254

In [62]:
results = {
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        0.7935,
        0.8370,
        0.8315
    ],
    "Precision": [
        0.8586,
        0.8624,
        0.8900
    ],
    "Recall": [
        0.7798,
        0.8624,
        0.8165
    ],
    "F1": [
        0.8173,
        0.8624,
        0.8517
    ]
}

results_df = pd.DataFrame(results)

results_df

                 Model  Accuracy  Precision  Recall      F1
0  Logistic Regression    0.7935     0.8586  0.7798  0.8173
1        Random Forest    0.8370     0.8624  0.8624  0.8624
2              XGBoost    0.8315     0.8900  0.8165  0.8517

In [63]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1782363160.965009  374352 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1782363160.966504  374352 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1782363163.135261  374352 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1782363173.018468  374352 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1782363173.019077  374352 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [64]:
model = Sequential([
    Dense(16, activation='relu', input_shape=(12,)),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.summary()

/media/hdd/multi-disease-prediction-using-ml-dl-flask-web-app/venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
E0000 00:00:1782363179.385388  374352 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 353 (1.38 KB)

 Trainable params: 353 (1.38 KB)

 Non-trainable params: 0 (0.00 B)

In [65]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [66]:
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - accuracy: 0.5000 - loss: 0.7669 - val_accuracy: 0.4865 - val_loss: 0.7372
Epoch 2/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5748 - loss: 0.6869 - val_accuracy: 0.6216 - val_loss: 0.6619
Epoch 3/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.6905 - loss: 0.6307 - val_accuracy: 0.7230 - val_loss: 0.6110
Epoch 4/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7483 - loss: 0.5903 - val_accuracy: 0.7838 - val_loss: 0.5710
Epoch 5/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7755 - loss: 0.5582 - val_accuracy: 0.7973 - val_loss: 0.5376
Epoch 6/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7806 - loss: 0.5300 - val_accuracy: 0.7973 - val_loss: 0.5114
Epoch 7/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7908 - loss: 0.5077 - val_accuracy: 0.8108 - val_loss: 0.4898
Epoch 8/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7925 - loss: 0.4902 - val_accuracy: 0.7973 - val_loss: 0.4788
Epoch 9/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7874 - loss: 0.4766 - val_accuracy: 0.8108 - val_loss: 0.4662
Epoch 10/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7925 - loss: 0.4655 - val_accuracy: 0.8108 - val_loss: 0.4585
Epoch 11/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7959 - loss: 0.4569 - val_accuracy: 0.8041 - val_loss: 0.4536
Epoch 12/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7976 - loss: 0.4513 - val_accuracy: 0.8041 - val_loss: 0.4475
Epoch 13/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7942 - loss: 0.4458 - val_accuracy: 0.8041 - val_loss: 0.4422
Epoch 14/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7993 - loss: 0.4417 - val_accuracy: 0.8041 - val_loss: 0.4375
Epoch 15/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7959 - loss: 0.4379 - val_accuracy: 0.8041 - val_loss: 0.4347
Epoch 16/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7976 - loss: 0.4340 - val_accuracy: 0.8041 - val_loss: 0.4317
Epoch 17/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7976 - loss: 0.4311 - val_accuracy: 0.8041 - val_loss: 0.4291
Epoch 18/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8027 - loss: 0.4282 - val_accuracy: 0.8108 - val_loss: 0.4287
Epoch 19/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8010 - loss: 0.4255 - val_accuracy: 0.8108 - val_loss: 0.4272
Epoch 20/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7993 - loss: 0.4233 - val_accuracy: 0.8108 - val_loss: 0.4251
Epoch 21/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8027 - loss: 0.4206 - val_accuracy: 0.8041 - val_loss: 0.4229
Epoch 22/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8010 - loss: 0.4188 - val_accuracy: 0.8108 - val_loss: 0.4228
Epoch 23/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8027 - loss: 0.4166 - val_accuracy: 0.8108 - val_loss: 0.4217
Epoch 24/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8027 - loss: 0.4146 - val_accuracy: 0.8108 - val_loss: 0.4210
Epoch 25/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8095 - loss: 0.4128 - val_accuracy: 0.8108 - val_loss: 0.4172
Epoch 26/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8112 - loss: 0.4109 - val_accuracy: 0.8108 - val_loss: 0.4174
Epoch 27/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8095 - loss: 0.4098 - val_accuracy: 0.8108 - val_loss: 0.4181
Epoch 28/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8112 - loss: 0.4085 - val_accuracy: 0.8108 - val_loss: 0.4187
Epoch 29/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8129 - loss: 0.4059 - val_accuracy: 0.8108 - val_loss: 0.4166
Epoch 30/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8129 - loss: 0.4046 - val_accuracy: 0.8108 - val_loss: 0.4156
Epoch 31/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8163 - loss: 0.4029 - val_accuracy: 0.8108 - val_loss: 0.4154
Epoch 32/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8146 - loss: 0.4007 - val_accuracy: 0.8108 - val_loss: 0.4163
Epoch 33/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8146 - loss: 0.3994 - val_accuracy: 0.8108 - val_loss: 0.4162
Epoch 34/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8180 - loss: 0.3978 - val_accuracy: 0.8176 - val_loss: 0.4150
Epoch 35/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8180 - loss: 0.3958 - val_accuracy: 0.8176 - val_loss: 0.4155
Epoch 36/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8231 - loss: 0.3950 - val_accuracy: 0.8243 - val_loss: 0.4140
Epoch 37/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8231 - loss: 0.3932 - val_accuracy: 0.8176 - val_loss: 0.4142
Epoch 38/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.8265 - loss: 0.3921 - val_accuracy: 0.8243 - val_loss: 0.4142
Epoch 39/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.8299 - loss: 0.3906 - val_accuracy: 0.8243 - val_loss: 0.4138
Epoch 40/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8282 - loss: 0.3891 - val_accuracy: 0.8176 - val_loss: 0.4158
Epoch 41/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8299 - loss: 0.3880 - val_accuracy: 0.8176 - val_loss: 0.4163
Epoch 42/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.8299 - loss: 0.3873 - val_accuracy: 0.8243 - val_loss: 0.4169
Epoch 43/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.8282 - loss: 0.3855 - val_accuracy: 0.8243 - val_loss: 0.4165
Epoch 44/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8299 - loss: 0.3845 - val_accuracy: 0.8243 - val_loss: 0.4144
Epoch 45/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.8282 - loss: 0.3834 - val_accuracy: 0.8243 - val_loss: 0.4154
Epoch 46/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8299 - loss: 0.3825 - val_accuracy: 0.8243 - val_loss: 0.4166
Epoch 47/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8350 - loss: 0.3812 - val_accuracy: 0.8243 - val_loss: 0.4135
Epoch 48/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8316 - loss: 0.3808 - val_accuracy: 0.8243 - val_loss: 0.4173
Epoch 49/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8333 - loss: 0.3792 - val_accuracy: 0.8243 - val_loss: 0.4147
Epoch 50/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8350 - loss: 0.3782 - val_accuracy: 0.8243 - val_loss: 0.4165

In [67]:
test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test
)

print("Test Accuracy:", test_accuracy)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8207 - loss: 0.3992
Test Accuracy: 0.820652186870575

In [68]:
y_pred_prob = model.predict(X_test)

y_pred = (y_pred_prob > 0.5).astype(int)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

In [69]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

Accuracy : 0.8206521739130435
Precision: 0.8584905660377359
Recall   : 0.8348623853211009
F1 Score : 0.8465116279069768

In [70]:
print(X.columns.tolist())

['age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalch', 'exang', 'oldpeak', 'slope']